#For run
podman/docker-compose -f docker-compose-lecrypt.yml up -d
# But for get ssl cert, you need step  by step changing yml file and data/nginx/nginx.conf file. And use init-letsencrypt.sh file(change domains and mail and use 1 or 0 for test or for get real cert).
# After that, you need add 2 record in cron

